name: Create Multi-Platform Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Build and Release Binaries
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the Code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Setup Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    # Step 3: Install PyInstaller
    - name: Install PyInstaller
      run: pip install pyinstaller

    # Step 4: Build Binaries
    strategy:
      matrix:
        platform: [windows, macos, linux]
    runs-on: ${{ matrix.platform }}-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build binary
      run: pyinstaller --onefile hello.py

    # Step 5: Upload binaries as artifacts
    - name: Upload binary
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.platform }}-hello
        path: dist/hello*