name: Create Multi-Platform Release

permissions:
  contents: write
  id-token: write

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.platform }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set Up Python Environment
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install PyInstaller
      run: pip install pyinstaller

    - name: Build Executable
      run: |
        pyinstaller --onefile hello.py
      working-directory: .

    - name: List dist directory contents
      run: |
        if ($env:RUNNER_OS -eq 'Windows') {
          dir dist
        } else {
          ls -alh dist
        }


    - name: Archive Executable
      run: |
        mkdir -p build_output
        mv dist/hello* build_output/

    - name: Upload Binaries
      uses: actions/upload-artifact@v3
      with:
        name: Executable-${{ matrix.platform }}
        path: build_output/*

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Create GitHub Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        files: build_output/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
